<?php

/**
 * Implements hook_services_resources().
 */

function nykz_service_services_resources() {

  $resources = array();

  $resources['nykzUser'] = array('operations' => array(),'actions' => array(),);

  $resources['nykzUser']['operations']['retrieve'] = array(
    'help' => 'Retrieve a nykzUser',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_retrieve',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'string',
        'description' => 'The username of the nykzUser to retrieve',
      ),
    ),
    'access arguments' => array('retrieve nykzUser'),
    );

  $resources['nykzUser']['operations']['create'] = array(
    'help' => 'create a nykzUser',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_create',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('data' => 'user'),
        'type' => 'string',
        'description' => 'The name of the nykz account',
      ),
      array(
        'name' => 'pw',
        'optional' => FALSE,
        'source' => array('data' => 'pw'),
        'type' => 'string',
        'description' => 'The password of the nykz account',
      ),
    ),
    'access arguments' => array('create nykzUser'),
    );

  $resources['nykzUser']['actions']['login'] = array(
    'help' => 'login with user & pw',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_login',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('data' => 'user'),
        'type' => 'string',
        'description' => 'The name of the nykz account',
      ),
      array(
        'name' => 'pw',
        'optional' => FALSE,
        'source' => array('data' => 'pw'),
        'type' => 'string',
        'description' => 'The password of the nykz account',
      ),
    ),
    'access arguments' => array('login nykzUser'),
    );

  return $resources;
}
