<?php

/**
 * Implements hook_services_resources().
 */

function nykz_service_services_resources() {

  $resources = array();

  $resources['nykzUser'] = array('operations' => array(),'actions' => array(),);

  $resources['nykzUser']['operations']['retrieve'] = array(
    'help' => 'Retrieve a nykzUser',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_retrieve',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'string',
        'description' => 'The username of the nykzUser to retrieve',
      ),
    ),
    'access callback' => '_nykz_return_true',
    );

  $resources['nykzUser']['operations']['create'] = array(
    'help' => 'create a nykzUser',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_create',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('data' => 'user'),
        'type' => 'string',
        'description' => 'The name of the nykz account',
      ),
      array(
        'name' => 'pw',
        'optional' => FALSE,
        'source' => array('data' => 'pw'),
        'type' => 'string',
        'description' => 'The password of the nykz account',
      ),
    ),
    'access callback' => '_nykz_return_true',
    );

  $resources['nykzUser']['actions']['login'] = array(
    'help' => 'login with user & pw',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzUser_resource'),
    'callback' => '_nykzUser_resource_login',
    'args' => array(
      array(
        'name' => 'user',
        'optional' => FALSE,
        'source' => array('data' => 'user'),
        'type' => 'string',
        'description' => 'The name of the nykz account',
      ),
      array(
        'name' => 'pw',
        'optional' => FALSE,
        'source' => array('data' => 'pw'),
        'type' => 'string',
        'description' => 'The password of the nykz account',
      ),
    ),
    'access callback' => '_nykz_return_true',
    );


  $resources['nykzBoard'] = array('operations' => array(),'actions' => array(),);

  $resources['nykzBoard']['operations']['index'] = array(
    'help' => 'list nykzBoard',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzBoard_resource'),
    'callback' => '_nykzBoard_resource_index',
    'access callback' => '_nykz_return_true',
    );

  $resources['nykzBoard']['operations']['retrieve'] = array(
    'help' => 'Retrieve a nykzBoard',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzBoard_resource'),
    'callback' => '_nykzBoard_resource_retrieve',
    'args' => array(
      array(
        'name' => 'boardname',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'string',
        'description' => 'The english name of the board',
      ),
    ),
    'access callback' => '_nykz_access_board',
    'access arguments append' => TRUE,
    );


  $resources['nykzPost'] = array('operations' => array(),'actions' => array(),);

  $resources['nykzPost']['operations']['index'] = array(
    'help' => 'list nykzPost',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzPost_resource'),
    'callback' => '_nykzPost_resource_index',
    'args' => array(
      array(
        'name' => 'boardname',
        'optional' => FALSE,
        'source' => array('path' => '0'),
        'type' => 'string',
        'description' => 'The english name of the board',
        ),
      array(
        'name' => 'start',
        'optional' => TRUE,
        'default value' => 999999,
        'source' => array('param' => 'start'),
        'type' => 'int',
        'description' => 'the start tip number',
        ),
      array(
        'name' => 'count',
        'optional' => TRUE,
        'default value' => 20,
        'source' => array('param' => 'count'),
        'type' => 'int',
        'description' => 'The number of posts',
        ),
      ),
    'access callback' => '_nykz_access_board',
    'access arguments append' => TRUE,
    );

  $resources['nykzPost']['operations']['retrieve'] = array(
    'help' => 'Retrieve a nykzPost',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzPost_resource'),
    'callback' => '_nykzPost_resource_retrieve',
    'args' => array(
      array(
        'name' => 'boardname',
        'optional' => FALSE,
        'source' => array('path' => '0'),
        'type' => 'string',
        'description' => 'The english name of the board',
      ),
      array(
        'name' => 'filename',
        'optional' => FALSE,
        'source' => array('path' => '1'),
        'type' => 'string',
        'description' => 'The filename',
      ),
      array(
        'name' => 'format',
        'optional' => TRUE,
        'default' => 'novt',
        'source' => array('path' => '2'),
        'type' => 'string',
        'description' => 'The format',
      ),
    ),
    'access callback' => '_nykz_access_board',
    'access arguments append' => TRUE,
    );
  $resources['nykzPost']['operations']['create'] = array(
    'help' => 'create a nykzPost',
    'file' => array('type' => 'inc','module' => 'nykz_service','name' => 'resources/nykzPost_resource'),
    'callback' => '_nykzPost_resource_create',
    'args' => array(
      array(
        'name' => 'boardname',
        'optional' => FALSE,
        'source' => array('path' => '0'),
        'type' => 'string',
        'description' => 'The english name of the board',
      ),
      array(
        'name' => 'title',
        'optional' => TRUE,
        'source' => array('data' => 'title'),
        'type' => 'string',
        'description' => 'The filename',
      ),
      array(
        'name' => 'content',
        'optional' => FALSE,
        'source' => array('data' => 'content'),
        'type' => 'string',
        'description' => 'The format',
      ),
      array(
        'name' => 'refilename',
        'optional' => TRUE,
        'source' => array('data' => 'refilename'),
        'type' => 'string',
        'description' => 'The format',
      ),
    ),
    'access callback' => '_nykz_access_board',
    'access arguments append' => TRUE,
    );
  return $resources;
}

function _nykz_access_board($boardName){
    global $user;
    $board = nykz_board_load_multiple(array($boardName),$user->name);
    return $board;
}

function _nykz_return_true(){
  return TRUE;
}