<?php


/*
 * 返回载入的板面信息
 * 如果一个用户没有进入某个板面的权限，则该板面不予返回
 */
function nykz_board_load_multiple($boardNames = array(), $account = NULL){
  variable_del("nykz_boards");
  $boards = variable_get("nykz_boards",FALSE);
  if(!$boards){
    nykz_board_refresh_all();
    $boards = variable_get("nykz_boards");
  }

  if(!$boardNames){
    $boardNames = array_keys($boards);
  }
  if(!$account){
    global $user;
    $account = $user;
  }

  $ret = array();
  foreach($boardNames as $boardName){
    $board = $boards[$boardName];
    if(!$board) continue;
    if($board['board_iskboard'] && !in_array($account->name, $board['board_klist'])){
      continue;
    }
    else{
      $ret[$boardName] = $board;
    }
  }

  return $ret;
}

function nykz_board_refresh_all(){
  $url = variable_get('nykz_config_pyserver')."/bbsboard";
  $res = file_get_contents($url);
  $arr = json_decode($res,TRUE);
  if($arr['message'] && $arr['message']['error'] && $arr['message']['no']){
    throw new Exception($arr['message']['error']);
  }
  elseif($arr['message']){
    foreach($arr['message'] as $boardname => $board){
      $arr['message'][$boardname] = nykz_board_format($board);
    }
    variable_set("nykz_boards",$arr['message']);
    return $arr['message'];
  }
  else{
    throw new Exception("pyRestful Server doesn't work!");
  }
}

function nykz_board_format($board){
  $board_formated = array();
  $board_formated['board_bm'] = split(" ", $board['BM']);
  $board_formated['board_name'] = $board['filename'];
  $board_formated['board_catagory'] = $board['title'][0];
  $board_title_split = split("\[|(\] ○ )|\u0000", $board['title']);
  $board_formated['board_title_split'] = $board_title_split;
  $board_formated['board_catagory'] = $board_title_split[0];
  $board_formated['board_catagory_name'] = $board_title_split[1];
  $board_formated['board_chinesename'] = $board_title_split[2];
  $board_formated['board_iskboard'] = !!$board['allow'];
  $board_formated['board_klist'] = $board['allow'];
  return $board_formated;
}