<?php


/*
 * 返回载入的板面信息
 * 如果一个用户没有进入某个板面的权限，则该板面不予返回
 * 不填写$username会返回所有板面
 */
function nykz_board_load_multiple($boardNames = array(), $username = NULL){
  $boards = nykz_board_refresh_all();

  if(!$boardNames){
    $boardNames = array_keys($boards);
  }

  $ret = array();
  foreach($boardNames as $boardName){
    $board = $boards[$boardName];
    if(!$board) continue;
    if($username 
      && $board['board_iskboard'] 
      && !in_array($username, $board['board_klist']
        )){
      continue;
    }
    if(in_array($board['board_name'], array("syssecurity", "MoneyAdmin","TrainingAdmin","Merchant","CrossPost","CrossAdmin","cnTest","mikexy"))){
      continue;
    }
    else{
      $ret[$boardName] = $board;
    }
  }

  return $ret;
}

function nykz_board_refresh_all(){
  $url = variable_get('nykz_config_pyserver')."/bbsboard";
  $res = file_get_contents($url);
  $arr = json_decode($res,TRUE);
  if(isset($arr['message']) && isset($arr['message']['error']) && $arr['message']['no']){
    throw new Exception($arr['message']['error']);
  }
  elseif(isset($arr['message'])){
    foreach($arr['message'] as $boardname => $board){
      $arr['message'][$boardname] = nykz_board_format($board);
    }
    return $arr['message'];
  }
  else{
    throw new Exception("pyRestful Server doesn't work!");
  }
}

function nykz_board_format($board){
  $board_formated = array();
  $board_formated['board_bm'] = split(" ", $board['BM']);
  $board_formated['board_name'] = $board['filename'];
  $board_formated['board_catagory'] = $board['title'][0];
  $board_title_split = split("\[|(\] ○ )|\u0000", $board['title']);
  $board_formated['board_title_split'] = $board_title_split;
  $board_formated['board_catagory'] = $board_title_split[0];
  $board_formated['board_catagory_name'] = $board_title_split[1];
  $board_formated['board_chinesename'] = $board_title_split[2];
  $board_formated['board_iskboard'] = !!$board['allow'];
  $board_formated['board_level'] = $board['level'];
  $board_formated['board_klist'] = $board['allow'];
  return $board_formated;
}
